workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Patch terminate_restart plugin (Swift fix)
        script: |
          # This patches the 'guard let' on non-optional 'engine' which causes build failures in modern Flutter
          echo "Searching for TerminateRestartPlugin.swift..."
          find . -name TerminateRestartPlugin.swift -print0 | xargs -0 sed -i '' 's/guard let flutterEngine = flutterViewController.engine else {/let flutterEngine = flutterViewController.engine; if false { \/\/ /g'
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build IPA for iOS
        script: |
          # Build the IPA without code signing (for validation/testing)
          # To enable code signing, you need to set up Apple Developer certificates in Codemagic UI
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your_email@example.com # Update this to your email
        notify:
          success: true
          failure: true
